/* 
 * This class facilitate the user creating a new avatar
 */
package frames;

import arena3.Arena;
import classes.*;
import com.sun.glass.events.KeyEvent;
import java.io.IOException;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import utilities.AudioPlayer;
import utilities.FrameManipulator;

/**
 * @author Scott Underwood
 * @author Shawn Ferdig
 */
public class CharacterCreationFrame extends javax.swing.JFrame {
    private Player user = new Player();
    private Player trueUser;
    String name;
    String role;
    AudioPlayer audioPlayer;
    FrameManipulator frameManipulator;
   
    /**
     * Creates new form CharacterCreationFrame
     */
    public CharacterCreationFrame() {

        initComponents();
        frameManipulator = new FrameManipulator();
        frameManipulator.centeredFrame(this);
        try {
            audioPlayer = new AudioPlayer();
        } 
        catch (UnsupportedAudioFileException | IOException | 
                LineUnavailableException ex) {
            System.out.println("Error 102");
        }
        knightPopUp.setVisible(false);
        magePopUp.setVisible(false);
        rangerPopUp.setVisible(false);
        hunterPopUp.setVisible(false);
        rolePanel.setVisible(false);
        confirmationLabel.setVisible(false);
        submit.setVisible(false);
        updateStats();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        newNameLabel1 = new javax.swing.JLabel();
        newName = new javax.swing.JTextField();
        rolePanel = new javax.swing.JPanel();
        knightSelection = new javax.swing.JButton();
        knightPopUp = new javax.swing.JLabel();
        rangerSelection = new javax.swing.JButton();
        rangerPopUp = new javax.swing.JLabel();
        hunterSelection = new javax.swing.JButton();
        hunterPopUp = new javax.swing.JLabel();
        mageSelection = new javax.swing.JButton();
        magePopUp = new javax.swing.JLabel();
        statLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        speedStat = new javax.swing.JLabel();
        mpStat = new javax.swing.JLabel();
        hpStat = new javax.swing.JLabel();
        intStat = new javax.swing.JLabel();
        strStat = new javax.swing.JLabel();
        dexStat = new javax.swing.JLabel();
        speedStatLabel1 = new javax.swing.JLabel();
        mpStatLabel1 = new javax.swing.JLabel();
        intStatLabel = new javax.swing.JLabel();
        hpStatLabel = new javax.swing.JLabel();
        strStatLabel = new javax.swing.JLabel();
        dexStatLabel = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        confirmationLabel = new javax.swing.JLabel();
        submitName = new javax.swing.JButton();
        goBack = new javax.swing.JButton();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newNameLabel1.setBackground(new java.awt.Color(0, 0, 0));
        newNameLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        newNameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        newNameLabel1.setText("WHO ARE YOU?");
        jLayeredPane1.add(newNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 220, 50));

        newName.setBackground(new java.awt.Color(255, 255, 255));
        newName.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        newName.setForeground(new java.awt.Color(0, 0, 0));
        newName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        newName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                newNameFocusLost(evt);
            }
        });
        newName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newNameMouseClicked(evt);
            }
        });
        newName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newNameActionPerformed(evt);
            }
        });
        newName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newNameKeyTyped(evt);
            }
        });
        jLayeredPane1.add(newName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 270, 50));

        rolePanel.setOpaque(false);
        rolePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        knightSelection.setBackground(new java.awt.Color(204, 0, 51));
        knightSelection.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        knightSelection.setForeground(new java.awt.Color(255, 255, 255));
        knightSelection.setText("Knight");
        knightSelection.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 10, true));
        knightSelection.setBorderPainted(false);
        knightSelection.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        knightSelection.setFocusable(false);
        knightSelection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                knightSelectionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                knightSelectionMouseExited(evt);
            }
        });
        knightSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knightSelectionActionPerformed(evt);
            }
        });
        rolePanel.add(knightSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 140, 50));

        knightPopUp.setBackground(new java.awt.Color(0, 0, 0));
        knightPopUp.setForeground(new java.awt.Color(255, 255, 255));
        knightPopUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        knightPopUp.setText("Specializes in physical attack and defense\n");
        knightPopUp.setFocusable(false);
        knightPopUp.setOpaque(true);
        rolePanel.add(knightPopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 240, 20));

        rangerSelection.setBackground(new java.awt.Color(51, 102, 0));
        rangerSelection.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        rangerSelection.setForeground(new java.awt.Color(255, 255, 255));
        rangerSelection.setText("Ranger");
        rangerSelection.setFocusable(false);
        rangerSelection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rangerSelectionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rangerSelectionMouseExited(evt);
            }
        });
        rangerSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rangerSelectionActionPerformed(evt);
            }
        });
        rolePanel.add(rangerSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 140, 50));

        rangerPopUp.setBackground(new java.awt.Color(0, 0, 0));
        rangerPopUp.setForeground(new java.awt.Color(255, 255, 255));
        rangerPopUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rangerPopUp.setText("Speedy enough to dodge attacks");
        rangerPopUp.setFocusable(false);
        rangerPopUp.setOpaque(true);
        rolePanel.add(rangerPopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 190, 20));

        hunterSelection.setBackground(new java.awt.Color(153, 153, 153));
        hunterSelection.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        hunterSelection.setForeground(new java.awt.Color(255, 255, 255));
        hunterSelection.setText("Hunter");
        hunterSelection.setFocusable(false);
        hunterSelection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hunterSelectionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hunterSelectionMouseExited(evt);
            }
        });
        hunterSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hunterSelectionActionPerformed(evt);
            }
        });
        rolePanel.add(hunterSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 140, 50));

        hunterPopUp.setBackground(new java.awt.Color(0, 0, 0));
        hunterPopUp.setForeground(new java.awt.Color(255, 255, 255));
        hunterPopUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hunterPopUp.setText("Can do it all, but none of it well ");
        hunterPopUp.setFocusable(false);
        hunterPopUp.setOpaque(true);
        rolePanel.add(hunterPopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 180, 20));

        mageSelection.setBackground(new java.awt.Color(0, 102, 255));
        mageSelection.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        mageSelection.setForeground(new java.awt.Color(255, 255, 255));
        mageSelection.setText("Mage");
        mageSelection.setFocusable(false);
        mageSelection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mageSelectionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mageSelectionMouseExited(evt);
            }
        });
        mageSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mageSelectionActionPerformed(evt);
            }
        });
        rolePanel.add(mageSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 140, 50));

        magePopUp.setBackground(new java.awt.Color(0, 0, 0));
        magePopUp.setForeground(new java.awt.Color(255, 255, 255));
        magePopUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        magePopUp.setText("Shoots magic missiles and defends against them ");
        magePopUp.setFocusable(false);
        magePopUp.setOpaque(true);
        rolePanel.add(magePopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 290, -1));

        statLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        statLabel.setForeground(new java.awt.Color(255, 255, 255));
        statLabel.setText("YOUR STATS");
        rolePanel.add(statLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 220, 50));

        roleLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        roleLabel.setForeground(new java.awt.Color(255, 255, 255));
        roleLabel.setText("WHAT ARE YOU?");
        rolePanel.add(roleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 220, 50));

        speedStat.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        speedStat.setForeground(new java.awt.Color(255, 255, 255));
        speedStat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        speedStat.setText("30");
        rolePanel.add(speedStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 180, 60, 50));

        mpStat.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        mpStat.setForeground(new java.awt.Color(255, 255, 255));
        mpStat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mpStat.setText("30");
        rolePanel.add(mpStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 110, 60, 50));

        hpStat.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        hpStat.setForeground(new java.awt.Color(255, 255, 255));
        hpStat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hpStat.setText("80");
        rolePanel.add(hpStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 50, 60, 50));

        intStat.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        intStat.setForeground(new java.awt.Color(255, 255, 255));
        intStat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        intStat.setText("3");
        rolePanel.add(intStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 110, 60, 50));

        strStat.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        strStat.setForeground(new java.awt.Color(255, 255, 255));
        strStat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        strStat.setText("3");
        rolePanel.add(strStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 50, 60, 50));

        dexStat.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        dexStat.setForeground(new java.awt.Color(255, 255, 255));
        dexStat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dexStat.setText("3");
        rolePanel.add(dexStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 180, 60, 50));

        speedStatLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        speedStatLabel1.setForeground(new java.awt.Color(51, 102, 0));
        speedStatLabel1.setText("SPEED");
        rolePanel.add(speedStatLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 180, 70, 50));

        mpStatLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        mpStatLabel1.setForeground(new java.awt.Color(0, 102, 255));
        mpStatLabel1.setText("AP");
        rolePanel.add(mpStatLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 110, 40, 50));

        intStatLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        intStatLabel.setForeground(new java.awt.Color(0, 102, 255));
        intStatLabel.setText("INT");
        rolePanel.add(intStatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 40, 50));

        hpStatLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        hpStatLabel.setForeground(new java.awt.Color(204, 0, 51));
        hpStatLabel.setText("HP");
        rolePanel.add(hpStatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, 40, 50));

        strStatLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        strStatLabel.setForeground(new java.awt.Color(204, 0, 51));
        strStatLabel.setText("STR");
        rolePanel.add(strStatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 50, 40, 50));

        dexStatLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        dexStatLabel.setForeground(new java.awt.Color(51, 102, 0));
        dexStatLabel.setText("DEX");
        rolePanel.add(dexStatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 50, 50));

        jLayeredPane1.add(rolePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 1210, 290));

        submit.setBackground(new java.awt.Color(102, 102, 102));
        submit.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("SUBMIT");
        submit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 25, true));
        submit.setBorderPainted(false);
        submit.setFocusable(false);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jLayeredPane1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 640, 180, 60));

        confirmationLabel.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        confirmationLabel.setForeground(new java.awt.Color(255, 255, 255));
        confirmationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmationLabel.setText(user.getName()+ " you have chosen the way of the "+user.getRole()+". Is this your path?");
        jLayeredPane1.add(confirmationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 1220, 70));

        submitName.setBackground(new java.awt.Color(102, 102, 102));
        submitName.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        submitName.setForeground(new java.awt.Color(255, 255, 255));
        submitName.setText("OK");
        submitName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        submitName.setBorderPainted(false);
        submitName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitNameActionPerformed(evt);
            }
        });
        jLayeredPane1.add(submitName, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 60, 50));

        goBack.setBackground(new java.awt.Color(102, 102, 102));
        goBack.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        goBack.setForeground(new java.awt.Color(255, 255, 255));
        goBack.setText("MAIN MENU");
        goBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        goBack.setBorderPainted(false);
        goBack.setFocusable(false);
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });
        jLayeredPane1.add(goBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 640, 180, 60));

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CharcterCreationBackground.PNG"))); // NOI18N
        BackGround.setFocusable(false);
        jLayeredPane1.add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Sets the players role to knight if a name is given
     * @param evt - button click
     */
    private void knightSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knightSelectionActionPerformed
      
        if(!(newName.getText().isEmpty())){
            audioPlayer.setTrack(2);
            audioPlayer.playOnce();
            name = newName.getText();
            trueUser = new Player(name , knightSelection.getText(), 1,5,2,2);
            confirmation();
        }
    }//GEN-LAST:event_knightSelectionActionPerformed

    private void newNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newNameActionPerformed
    }//GEN-LAST:event_newNameActionPerformed
   
    /**
     * Sets the player role and name if a name is given and exits the frame
     * @param evt -  button click
     */
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
       
        if(!(newName.getText().isEmpty())){
            name = newName.getText();
            trueUser.setName(name);
            Arena.CUR_PLAYER = trueUser;
            audioPlayer.setTrack(2);
            audioPlayer.playOnce();
            TravelFrame travelFrame = new TravelFrame();
            travelFrame.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_submitActionPerformed
    
    /**
     * Sets the players role to Ranger if a name is given
     * @param evt - button click
     */
    private void rangerSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rangerSelectionActionPerformed
      
        if(!(newName.getText().isEmpty())){
            audioPlayer.setTrack(2);
            audioPlayer.playOnce();
            name = newName.getText();
            trueUser = new Player(name ,rangerSelection.getText(), 1,2,2,5);
            confirmation();
        }
    }//GEN-LAST:event_rangerSelectionActionPerformed
    
    /**
     * Sets the players role to hunter if a name is given
     * @param evt - button click
     */
    private void hunterSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hunterSelectionActionPerformed
      
        if(!(newName.getText().isEmpty())){
            audioPlayer.setTrack(2);
            audioPlayer.playOnce();
            name = newName.getText();
            trueUser = new Player(name, hunterSelection.getText(), 1,3,3,3);
            confirmation();
        }
    }//GEN-LAST:event_hunterSelectionActionPerformed

    /**
     * Sets the players role to Mage if a name is given
     * @param evt - button click
     */
    private void mageSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mageSelectionActionPerformed
       
        if(!(newName.getText().isEmpty())){
            audioPlayer.setTrack(2);
            audioPlayer.playOnce();
            name = newName.getText();
            trueUser = new Player(name,mageSelection.getText(), 1,2,5,2);
            confirmation();
        }
    }//GEN-LAST:event_mageSelectionActionPerformed

    /**
     * Sets the stats preview to the Knights stats, shows the knight's 
     * description
     * @param evt - mouse enter
     */
    private void knightSelectionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_knightSelectionMouseEntered

        knightPopUp.setVisible(true);
        role = knightSelection.getText();
        user = new Player(name, role, 5, 2, 2);
        updateStats();
        
    }//GEN-LAST:event_knightSelectionMouseEntered

    /**
     * On mouse exit reset stat preview to current selected role, hide the
     * knights description
     * @param evt mouse enter
     */
    private void knightSelectionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_knightSelectionMouseExited
        
        knightPopUp.setVisible(false);
        updateOnExit();
    }//GEN-LAST:event_knightSelectionMouseExited
    
    /**
     * On mouse enter show the mage description and show potential stats
     * @param evt mouse enter
     */
    private void mageSelectionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mageSelectionMouseEntered

        magePopUp.setVisible(true);
        role = mageSelection.getText();
        user = new Player(name, role, 2, 5, 2);
        updateStats();
    }//GEN-LAST:event_mageSelectionMouseEntered
      
    /**
     * On mouse exit reset stat preview to current selected role, hide the
     * mage description
     * @param evt mouse enter
     */
    private void mageSelectionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mageSelectionMouseExited

        magePopUp.setVisible(false);
        updateOnExit();
    }//GEN-LAST:event_mageSelectionMouseExited

    /**
     * On mouse enter show the ranger description and show potential stats
     * @param evt mouse enter
     */
    private void rangerSelectionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rangerSelectionMouseEntered

        rangerPopUp.setVisible(true);
        role = rangerSelection.getText();
        user = new Player(name, role, 2, 2, 5);
        updateStats();
    }//GEN-LAST:event_rangerSelectionMouseEntered

    /**
     * On mouse exit reset stat preview to current selected role, hide the
     * ranger description
     * @param evt mouse enter
     */
    private void rangerSelectionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rangerSelectionMouseExited

        rangerPopUp.setVisible(false);
        updateOnExit();
    }//GEN-LAST:event_rangerSelectionMouseExited

    
    /**
     * On mouse enter show the Hunter description and show potential stats
     * @param evt mouse enter
     */
    private void hunterSelectionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hunterSelectionMouseEntered

        hunterPopUp.setVisible(true);
        role = hunterSelection.getText();
        user = new Player(name, role, 3, 3, 3);
        updateStats();
    }//GEN-LAST:event_hunterSelectionMouseEntered

    /**
     * On mouse exit reset stat preview to current selected role, hide the
     * hunter description
     * @param evt mouse enter
     */
    private void hunterSelectionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hunterSelectionMouseExited
  
        hunterPopUp.setVisible(false);
        updateOnExit();
    }//GEN-LAST:event_hunterSelectionMouseExited

    /**
     * Resets the player's name when clicking on the name text box
     * @param evt on click
     */
    private void newNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newNameMouseClicked

        newName.setText(null);
        updateStats();
    }//GEN-LAST:event_newNameMouseClicked

    /**
     * Navigates to the main menu
     * @param evt 
     */
    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
    
        audioPlayer.setTrack(1);
        audioPlayer.playOnce();
        StartFrame startFrame = new StartFrame();
        startFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_goBackActionPerformed

    /**
     * Set the player's name when the name text box focus is lost
     * @param evt focus lost
     */
    private void newNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newNameFocusLost
        
        name = newName.getText();
        user.setName(name);
        
    }//GEN-LAST:event_newNameFocusLost

    private void newNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newNameKeyTyped
    }//GEN-LAST:event_newNameKeyTyped

    /**
     * Sets the player's name, makes the role panel visible and makes
     * name not visible
     * @param evt enter key pressed
     */
    private void newNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newNameKeyPressed
       
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(!(newName.getText().isEmpty())){
                audioPlayer.setTrack(2);
                audioPlayer.playOnce();
                name = newName.getText();
                user.setName(name);
                confirmationLabel.setText(name+" you have chosen the way of the "
                        +user.getRole()+". Is this your path?");
                rolePanel.setVisible(true);
                submitName.setVisible(false);
            }
        }
    }//GEN-LAST:event_newNameKeyPressed

     /**
     * Sets the player's name, makes the role panel visible, and sets submit
     * name not visible
     * @param evt submitName button pressed
     */
    private void submitNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitNameActionPerformed
        if(!(newName.getText().isEmpty())){
            audioPlayer.setTrack(2);
            audioPlayer.playOnce();
            submitName.setVisible(false);
            name = newName.getText();
            user.setName(name);
            confirmationLabel.setText(name+" you have chosen the way of the "
                    +user.getRole()+". Is this your path?");
            rolePanel.setVisible(true);
        }
    }//GEN-LAST:event_submitNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharacterCreationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharacterCreationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharacterCreationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharacterCreationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharacterCreationFrame().setVisible(true);
            }
        });
    }
    
    /**
     * Sets the preview stats
     */
    private void updateStats(){

        strStat.setText(Integer.toString(user.getStr()));
        intStat.setText(Integer.toString(user.getMag()));
        dexStat.setText(Integer.toString(user.getDex()));
        hpStat.setText(Integer.toString(user.getMaxHp()));
        mpStat.setText(Integer.toString(user.getMaxMp()));
        speedStat.setText(Integer.toString(user.getSpeed()));
    }
    
    /**
     * Resets preview stats to the current selected role, if no role is selected
     * shows default values.
     */
    private void updateOnExit(){
        
        if(trueUser == null){
            strStat.setText(Integer.toString(user.getStr()));
            intStat.setText(Integer.toString(user.getMag()));
            dexStat.setText(Integer.toString(user.getDex()));
            hpStat.setText(Integer.toString(user.getMaxHp()));
            mpStat.setText(Integer.toString(user.getMaxMp()));
            speedStat.setText(Integer.toString(user.getSpeed()));
        }
        else{
            strStat.setText(Integer.toString(trueUser.getBaseStr()));
            intStat.setText(Integer.toString(trueUser.getBaseMag()));
            dexStat.setText(Integer.toString(trueUser.getBaseDex()));
            hpStat.setText(Integer.toString(trueUser.getMaxHp()));
            mpStat.setText(Integer.toString(trueUser.getMaxMp()));
            speedStat.setText(Integer.toString(trueUser.getSpeed())); 
        }   
    }
    
    /**
     * Shows the conformation text and submit button when a role is chosen
     */
    public void confirmation(){
        
        confirmationLabel.setText(name+ " has chosen the way of the "+
                user.getRole()+". Is this your path?");
        confirmationLabel.setVisible(true);
        submit.setVisible(true); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel confirmationLabel;
    private javax.swing.JLabel dexStat;
    private javax.swing.JLabel dexStatLabel;
    private javax.swing.JButton goBack;
    private javax.swing.JLabel hpStat;
    private javax.swing.JLabel hpStatLabel;
    private javax.swing.JLabel hunterPopUp;
    private javax.swing.JButton hunterSelection;
    private javax.swing.JLabel intStat;
    private javax.swing.JLabel intStatLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel knightPopUp;
    private javax.swing.JButton knightSelection;
    private javax.swing.JLabel magePopUp;
    private javax.swing.JButton mageSelection;
    private javax.swing.JLabel mpStat;
    private javax.swing.JLabel mpStatLabel1;
    private javax.swing.JTextField newName;
    private javax.swing.JLabel newNameLabel1;
    private javax.swing.JLabel rangerPopUp;
    private javax.swing.JButton rangerSelection;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JPanel rolePanel;
    private javax.swing.JLabel speedStat;
    private javax.swing.JLabel speedStatLabel1;
    private javax.swing.JLabel statLabel;
    private javax.swing.JLabel strStat;
    private javax.swing.JLabel strStatLabel;
    private javax.swing.JButton submit;
    private javax.swing.JButton submitName;
    // End of variables declaration//GEN-END:variables
}

